openapi: 3.1.0
info:
  version: 1.0.0
  title: <Contact App>
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    <uygulamanızın açıklaması>
tags:
  # kullanacağınız etiketler
servers:
  - url: <http://localhost:10000>
  - url: <https://contact-app-swagger.onrender.com>
  - url: https://hw2-mongodb-pl0r.onrender.com # Render linki
paths:
  # burada uç noktaların bağlantıları olacak
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
